# Generated by Django 4.2.11 on 2024-04-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SummarizeFiles",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("doc_name", models.CharField(max_length=100)),
                ("sum_content", models.CharField(max_length=250)),
            ],
        ),
    ]
