# Generated by Django 4.2.11 on 2024-04-01 19:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("document", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SummarizeFiles",
            new_name="FileDB",
        ),
    ]
