# Generated by Django 4.2.11 on 2024-04-01 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("document", "0002_rename_summarizefiles_filedb"),
    ]

    operations = [
        migrations.CreateModel(
            name="queryDB",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("doc_name", models.CharField(max_length=100)),
                ("sum_content", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="SumDB",
            fields=[
                ("doc_id", models.AutoField(primary_key=True, serialize=False)),
                ("doc_name", models.CharField(max_length=100)),
                ("sum_content", models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name="FileDB",
        ),
        migrations.AddField(
            model_name="querydb",
            name="doc_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="document.sumdb"
            ),
        ),
    ]
