# Generated by Django 4.2.11 on 2024-04-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("document", "0004_remove_querydb_sum_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="querydb",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
