# Generated by Django 4.2.11 on 2024-04-02 20:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("document", "0005_alter_querydb_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SumDB",
            new_name="FileDB",
        ),
        migrations.DeleteModel(
            name="queryDB",
        ),
    ]
