# Generated by Django 4.2.11 on 2024-04-03 02:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("document", "0007_filedb_keyword"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filedb",
            name="keyword",
            field=models.CharField(default="None", max_length=150),
        ),
    ]
