# Generated by Django 4.2.11 on 2024-04-03 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("document", "0008_alter_filedb_keyword"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocInfo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(default="None", max_length=50)),
                (
                    "doc_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="document.docinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SumDoc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sum_content", models.CharField(max_length=250)),
                (
                    "doc_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="document.docinfo",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="FileDB",
        ),
    ]
