# Generated by Django 4.2.11 on 2024-04-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("document", "0009_docinfo_keyword_sumdoc_delete_filedb"),
    ]

    operations = [
        migrations.AddField(
            model_name="docinfo",
            name="url",
            field=models.CharField(default="", max_length=150),
        ),
    ]
