# Generated by Django 4.2.11 on 2024-04-03 16:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("document", "0010_docinfo_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="keyword",
            old_name="keyword",
            new_name="kwd",
        ),
    ]
